# Generated by Django 4.0.4 on 2022-05-24 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedTickets',
            fields=[
                ('ticket_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Registered_user', models.CharField(max_length=50)),
                ('movie_name', models.CharField(max_length=50)),
                ('tickets_booked', models.IntegerField(default=1000)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'User Tickets',
                'verbose_name_plural': 'User Tickets',
            },
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Tickets', 'verbose_name_plural': 'Tickets details'},
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='id',
        ),
        migrations.AddField(
            model_name='tickets',
            name='Total',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tickets',
            name='available',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tickets',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='movie_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
