# Generated by Django 4.0.4 on 2022-05-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_tickets_reserved_by_tickets_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='movie_id',
            field=models.CharField(default='M-1001', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='movie_name',
            field=models.CharField(max_length=50),
        ),
    ]
