# Generated by Django 4.0.4 on 2022-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_reservedtickets_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedtickets',
            name='price',
            field=models.IntegerField(default=400),
        ),
    ]
