# Generated by Django 4.0.4 on 2022-05-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_reservedtickets_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
